---
title: "RNA-seq course - week 4. Hypergeometric tests"
author: "Oleksandr Petrenko"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    code_folding: hide
    df_print: paged
    highlights: pygments
    number_sections: yes
    self_contained: yes
    theme: default
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
editor_options: 
  chunk_output_type: inline
---

## Setup

```{r setup}
knitr::opts_knit$set(root.dir = '~/Rstudio/2023_rnaseq_course/week4')
setwd("~/Rstudio/2023_rnaseq_course/week4")
```

# for plant folks: http://systemsbiology.cau.edu.cn/PlantGSEA/download.php

```{r install-packages}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("fgsea")
```

```{r}
library(fgsea)
library(tidyverse)
```

```{r}
adapelene_dmso <- read.csv("01_datasets/02_results_adapalene_dmso.csv")
tazarotene_dmso <- read.csv("01_datasets/02_results_tazarotene_dmso.csv")
getwd()
hallmark <- gmtPathways("01_datasets/h.all.v2023.1.Hs.symbols.gmt")
```

```{r}
adapelene_dmso <- adapelene_dmso %>% dplyr::filter(!is.na(padj)) %>% dplyr::filter(!is.na(log2FoldChange))
```


```{r}
ranked_a_d <- adapelene_dmso %>% mutate(rank = (log2FoldChange * abs(-log10(padj)))) %>% 
  select(X, rank) %>% tibble::deframe()
```

```{r}
library(stats)
```


```{r}
fgseaRes_a_d <- fgsea(pathways = hallmark, stats = ranked_a_d)
```



```{r}
fgseaRes_a_d
```

