---
title: "RNA-seq course - week 4. Hypergeometric tests"
author: "Oleksandr Petrenko"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    code_folding: hide
    df_print: paged
    highlights: pygments
    number_sections: yes
    self_contained: yes
    theme: default
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
editor_options: 
  chunk_output_type: inline
---

## Setup

```{r setup}
knitr::opts_knit$set(root.dir = '~/Rstudio/2023_rnaseq_course/week4')
setwd("~/Rstudio/2023_rnaseq_course/week4")
```


```{r install-packages}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("pathview")
BiocManager::install("biomaRt")
```

```{r}
library(pathview)
library(biomaRt)
```

```{r}
adapelene_dmso <- read.csv("01_datasets/02_results_adapalene_dmso.csv")
adapelene_dmso
```

```{r}
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
```
```{r}
listAttributes(ensembl) %
```


```{r}
biomart_list <- getBM(filter = "hgnc_symbol", 
                      attributes = c("hgnc_symbol", "entrezgene_id"),
                      values = adapelene_dmso$X, mart = ensembl)
```
```{r}
adapelene_dmso <- left_join(adapelene_dmso %>% rename(hgnc_symbol = X), biomart_list, by = "hgnc_symbol")
```

```{r}
adapelene_dmso
```


```{r}
logFC <- adapelene_dmso$log2FoldChange
names(logFC) <- adapelene_dmso$entrezgene_id
```
```{r}
pathview(gene.data = logFC, 
         pathway.id = "hsa04310", 
         species = "hsa", 
         kegg.native = T)
```

